### ISSUE TITLE
Decal Support

### ISSUE THREAD

**Issue by sonich2401** [matt-hayward/olcPGEX_AnimatedSprite#16]
With the release of the new and improved PGE 2.0 it would be nice to have Decal support so that users can utilize the most out of their programs by being able to draw thousands of sprites to the  screen at once.

**Comment by matt-hayward** [comment]
Yep, this is something I have planned for a version 2 of this PGEX.

It's something I'll be looking at doing very soon.

**Comment by matt-hayward** [comment]
This has now been resolved in v2.0.0
